{ "ProductKey": "a1yw5SXDnKc", "DeviceName": "862815030012015", "DeviceSecret": "krEFl8PwYuiSwvANKbMg5bcWcy3pHabT" }
  865860042654765,key=a1yw5SXDnKc;secret=0oXsLpZcBGwiKkgxMpWGHH4ffQKwlPlr;region=cn-shanghai;type=9

  {
    "ProductKey": "a1yw5SXDnKc",
    "DeviceName": "865860042654765",
    "DeviceSecret": "0oXsLpZcBGwiKkgxMpWGHH4ffQKwlPlr"
  }
  123